### ISSUE TITLE
com.qcloud.cmq.Json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]

### ISSUE THREAD

**Issue by peica** [tencentyun/cmq-java-sdk#2]
调用publishMessage时，当发的是以下数据，会报com.qcloud.cmq.Json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]的错误.

Ch0yMDE3LTEyLTA3VDEwOjMyOjA3LjE4MiswODowMBIdaW90aHVibGl2ZXNlcnZlci1zZXJ2ZXItZXZlbnQaCGttdi5rbXYuIlcSNGNsYXNzIGNuLmthbWF2YS5pb3RodWIuc2VydmljZXMuaW50ZXJuYWwuTmF0aXZlUGM5MDEaFzIwMTctMTItMDdUMTA6MzI6MDcuMTQ1IgYIq/WPsQI=

**Comment by ywj1352** [comment]
我是 获取 数据 报 这个错  你是怎么解决的
