### ISSUE TITLE
代码不符合规范的太多

### ISSUE THREAD

**Issue by ashuai1227** [tencentyun/cmq-java-sdk#23]
Message等类属性为public的。
CMQServerException类属性为private的，但没有get方法
Topic类又为protected
用规范 一扫描全是问题，能否按照规范整理一遍。
建议代码提交前，先用相关工具扫描一下是否有bug或漏洞。
另外，代码里面所有
       JSONObject jsonObj = new JSONObject(result);
        CMQTool.checkResult(result);
这两行代码应该互换一下，返回为null的时候 第一行就已经报空指针异常了。

**Comment by wchaowu** [comment]
感觉这个sdk不是java程序员写的
