### ISSUE TITLE
CMQHttp中的字符串比较"this.url != url"有问题

### ISSUE THREAD

**Issue by JustDoNow** [tencentyun/cmq-java-sdk#5]
这个比较导致每次都是false
`
public String request(String method, String url, String req, int userTimeout) throws Exception {
		String result = "";
		BufferedReader in = null;
		try {
			if (this.url != url)
				this.newHttpConnection(url);
`

**Comment by JustDoNow** [comment]
`
public String request(String method, String url, String req, int userTimeout) throws Exception {

    String result = "";
    BufferedReader in = null;
		try {
			if (this.url != url)
				this.newHttpConnection(url);
`

**Comment by JustDoNow** [comment]
![Uploading image.png…]()

**Comment by JustDoNow** [comment]
![image](https://user-images.githubusercontent.com/8234204/57227598-5e148180-7044-11e9-9b1e-f3cba034191f.png)
这个代码

**Comment by yorkhellen** [comment]
已修复
