### ISSUE TITLE
CMQHttp 过早关闭问题

### ISSUE THREAD

**Issue by AdolphL** [tencentyun/cmq-java-sdk#6]
![image](https://user-images.githubusercontent.com/30362951/57357810-6be21800-71a6-11e9-9dd4-e2816a2dc6fa.png)

请检查下这里是否丢掉了,   conn.disconnect(); 将connection关闭, 如果你想复用连接，那么请不要使用in.close()将response 流关闭。

**Comment by yorkhellen** [comment]
1.0.7版本处理了该问题，已经更新了新的client
