### ISSUE TITLE
CMQHttp产生java.lang.IllegalStateException: connect in progress错误

### ISSUE THREAD

**Issue by selway** [tencentyun/cmq-java-sdk#7]
相关#5 
![image](https://user-images.githubusercontent.com/6679547/57598573-509c5180-7586-11e9-9081-71e5bb54836f.png)

![image](https://user-images.githubusercontent.com/6679547/57598649-a244dc00-7586-11e9-94f0-44f5688f4962.png)
虽然 #5 比较生效，但是连接没有关闭，修改`requestMethod`会发生标题中的异常

**Comment by yorkhellen** [comment]
1.0.7版本处理了该问题，已经更新了新的client
